@AutoDetail.Host_HostAddress = http://localhost:5245



GET {{AutoDetail.Host_HostAddress}}/api/users/

###

GET {{AutoDetail.Host_HostAddress}}/api/users/7bf3272e-e8e2-431e-bade-20f1675d5617

###

GET {{AutoDetail.Host_HostAddress}}/api/users/GetByIds?ids=7bf3272e-e8e2-431e-bade-20f1675d5617&ids=a8f6a548-f091-4625-8921-672d580d55cc

###
POST {{AutoDetail.Host_HostAddress}}/api/users
content-type: application/json
{
  "firstName": "TestName",
  "lastName": "TestLastName"
}

###
PUT {{AutoDetail.Host_HostAddress}}/api/users/
content-type: application/json
  {
    "id": "dbd7a6bd-4c63-4367-8e10-6fa1844a8865",
    "firstName": "TestNameUpdated",
    "lastName": "TestLastName",
    "passwordHash": null,
    "email": null,
    "phone": "+79999999999",
    "updatedAt": null,
    "isVerified": false,
    "isAdmin": false,
    "paymentDetail": null,
    "address": null
  }